# Basic Jekyll Settings
encoding: utf-8
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title

# Exclude from processing
exclude:
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules

# Minimal Light Theme
# https://github.com/yaoyao-liu/minimal-light
remote_theme: yaoyao-liu/minimal-light

# Basic Information
title: Andrew Hundt
position: Computing Innovation Fellow
affiliation: Carnegie Mellon University
affiliation_link: https://www.cmu.edu/
affiliation_logo: ./assets/img/cmu.png
email: ATHundt (at) gmail.com

# Repository Information
repository: ahundt/ahundt.github.io

# Search Engine Optimization
keywords: Andrew Hundt, Robotics, AI, Machine Learning, Responsible AI, Equity, Diversity, Inclusion
description: Andrew Hundt's research on AI, Robotics, Deep Learning, Responsible AI, and AI Ethics
canonical: https://ahundt.github.io/

# Social Links
google_scholar: https://scholar.google.com/citations?user=N0JJHwkAAAAJ
github_link: https://github.com/ahundt
github_username: ahundt
linkedin: https://www.linkedin.com/in/andrewhundt
twitter: https://twitter.com/athundt
mastodon: https://mastodon.social/@ahundt
bluesky: https://bsky.app/profile/ahundt.bsky.social

# Profile Picture
avatar: https://0.gravatar.com/avatar/fb975596131ce08ea7e7472f09b8209d?d=https%3A%2F%2Fidenticons.github.com%2Fd7ccb841e1c86abdc1d1d6e6bacb6f17.png&r=x&s=200

# Display Options
enable_footnote: false
enable_last_update: false
auto_dark_mode: false
font: "Serif" # Serif or Sans Serif
font_size: "normal" # small, normal, large

# Google Analytics (optional)
google_analytics: UA-46300578-1

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap